<!--<h3>This new page is generated by CRM/Membershipperiods/Page/MembershipPeriods.php</h3>-->
<h3>Membership periods</h3>

<table>
<tr><th>Membership</th><th>Start date</th><th>End date</th></tr>
{foreach name=data item=row from=$data}
  <tr>
    <td>{$row.membership_id}</td>
    <td>{$row.start_date}</td>
    <td>{$row.end_date}</td>
{/foreach}

